"""create_initial_core_tables

Revision ID: 4fe0711f2a3e
Revises:
Create Date: 2026-09-27 21:10:16.594779

"""

from typing import Sequence, Union

import pgvector
import pgvector.sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4fe0711f2a3e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Enable pgvector extension before creating tables with Vector columns
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repositories",
        sa.Column("github_repo_id", sa.Integer(), nullable=False),
        sa.Column("owner", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("default_branch", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_repositories_github_repo_id"), "repositories", ["github_repo_id"], unique=True
    )
    op.create_table(
        "code_chunks",
        sa.Column("repo_id", sa.UUID(), nullable=False),
        sa.Column("file_path", sa.String(length=1024), nullable=False),
        sa.Column("start_line", sa.Integer(), nullable=False),
        sa.Column("end_line", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["repo_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_code_chunks_content_hash"), "code_chunks", ["content_hash"], unique=False
    )
    op.create_index(op.f("ix_code_chunks_file_path"), "code_chunks", ["file_path"], unique=False)
    op.create_index(op.f("ix_code_chunks_repo_id"), "code_chunks", ["repo_id"], unique=False)
    op.create_table(
        "code_symbols",
        sa.Column("chunk_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("symbol_type", sa.String(length=50), nullable=False),
        sa.Column("scope_path", sa.String(length=512), nullable=True),
        sa.Column("signature", sa.Text(), nullable=True),
        sa.Column("docstring", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["chunk_id"], ["code_chunks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_code_symbols_chunk_id"), "code_symbols", ["chunk_id"], unique=False)
    op.create_index(op.f("ix_code_symbols_name"), "code_symbols", ["name"], unique=False)
    op.create_index(
        op.f("ix_code_symbols_symbol_type"), "code_symbols", ["symbol_type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_code_symbols_symbol_type"), table_name="code_symbols")
    op.drop_index(op.f("ix_code_symbols_name"), table_name="code_symbols")
    op.drop_index(op.f("ix_code_symbols_chunk_id"), table_name="code_symbols")
    op.drop_table("code_symbols")
    op.drop_index(op.f("ix_code_chunks_repo_id"), table_name="code_chunks")
    op.drop_index(op.f("ix_code_chunks_file_path"), table_name="code_chunks")
    op.drop_index(op.f("ix_code_chunks_content_hash"), table_name="code_chunks")
    op.drop_table("code_chunks")
    op.drop_index(op.f("ix_repositories_github_repo_id"), table_name="repositories")
    op.drop_table("repositories")

    # ... drop tables ...
    op.execute("DROP EXTENSION IF EXISTS vector")

    # ### end Alembic commands ###
