"""GitHub Pull Request dispatcher creating branches, committing patches, and opening PRs."""

import base64
import logging
from typing import Any

import httpx

from agent_core.agent.state import FilePatch, VerificationResult
from agent_core.core.config import get_settings
from agent_core.domain.schemas.approvals import PullRequestResult
from agent_core.services.github.client import GitHubAppClient

logger = logging.getLogger(__name__)


class GitHubPRDispatcher:
    """Dispatches approved patches to GitHub by creating branches, committing, and opening PRs."""

    def __init__(
        self,
        github_client: GitHubAppClient | None = None,
        base_url: str = "https://api.github.com",
    ) -> None:
        self.github_client = github_client or GitHubAppClient()
        self.base_url = base_url.rstrip("/")
        self.settings = get_settings()

    def format_pr_body(
        self,
        issue_id: int,
        problem_statement: str,
        remediation_plan: str,
        patches: list[FilePatch],
        verification_result: VerificationResult,
    ) -> str:
        """Constructs a comprehensive, audited markdown report for the Pull Request."""
        patch_summaries = "\n".join(f"- `{p.file_path}`: {p.rationale}" for p in patches)
        return (
            f"## 🤖 Autonomous AI Bug Remediation Report\n\n"
            f"**Closes #{issue_id}**\n\n"
            f"### 🎯 Problem Statement\n{problem_statement}\n\n"
            f"### 📋 Remediation Plan\n{remediation_plan}\n\n"
            f"### 🛡️ Air-Gapped Sandbox Verification\n"
            f"- **Outcome**: PASSED ✅\n"
            f"- **Exit Code**: `{verification_result.exit_code}`\n"
            f"- **Network Policy**: Air-gapped (`network_mode='none'`)\n\n"
            f"<details>\n<summary><b>Test Output (Click to expand)</b></summary>\n\n"
            f"```text\n{verification_result.stdout.strip()}\n```\n"
            f"</details>\n\n"
            f"### 📝 Modified Files\n{patch_summaries}\n\n"
            f"---\n*Generated by Autonomous AI Software Engineer Agent. "
            f"Audited and approved via Human-in-the-Loop Governance Gate.*"
        )

    async def dispatch_pull_request(
        self,
        owner: str,
        repo: str,
        base_branch: str,
        feature_branch: str,
        title: str,
        body: str,
        files_to_commit: dict[str, str],
        installation_id: int | None = None,
    ) -> PullRequestResult:
        """Executes full GitHub PR creation workflow using GitHub App installation tokens."""
        # Check if running in mock/test mode
        if "mock" in self.settings.GITHUB_PRIVATE_KEY.get_secret_value():
            logger.info("Using mock PR dispatcher for %s/%s", owner, repo)
            return PullRequestResult(
                pr_number=101,
                pr_url=f"https://github.com/{owner}/{repo}/pull/101",
                branch_name=feature_branch,
                title=title,
                body=body,
            )

        assert installation_id is not None, "installation_id required for production PR dispatch"
        token = await self.github_client.get_installation_access_token(installation_id)
        headers = {
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        }

        async with httpx.AsyncClient(base_url=self.base_url, headers=headers) as client:
            # 1. Get base branch commit SHA
            ref_resp = await client.get(f"/repos/{owner}/{repo}/git/ref/heads/{base_branch}")
            ref_resp.raise_for_status()
            base_sha = ref_resp.json()["object"]["sha"]

            # 2. Create feature branch
            create_branch_resp = await client.post(
                f"/repos/{owner}/{repo}/git/refs",
                json={"ref": f"refs/heads/{feature_branch}", "sha": base_sha},
            )
            if create_branch_resp.status_code not in (201, 422):
                create_branch_resp.raise_for_status()

            # 3. Commit modified files to feature branch
            for file_path, content in files_to_commit.items():
                content_path = file_path.strip().lstrip("/")
                file_sha = None
                get_file_resp = await client.get(
                    f"/repos/{owner}/{repo}/contents/{content_path}?ref={feature_branch}"
                )
                if get_file_resp.status_code == 200:
                    file_sha = get_file_resp.json().get("sha")

                b64_content = base64.b64encode(content.encode("utf-8")).decode("utf-8")
                commit_payload: dict[str, Any] = {
                    "message": f"fix({content_path}): apply verified AI patch",
                    "content": b64_content,
                    "branch": feature_branch,
                }
                if file_sha:
                    commit_payload["sha"] = file_sha

                put_resp = await client.put(
                    f"/repos/{owner}/{repo}/contents/{content_path}",
                    json=commit_payload,
                )
                put_resp.raise_for_status()

            # 4. Open Pull Request
            pr_payload = {
                "title": title,
                "head": feature_branch,
                "base": base_branch,
                "body": body,
                "maintainer_can_modify": True,
            }
            pr_resp = await client.post(f"/repos/{owner}/{repo}/pulls", json=pr_payload)
            pr_resp.raise_for_status()
            pr_data = pr_resp.json()

            return PullRequestResult(
                pr_number=pr_data["number"],
                pr_url=pr_data["html_url"],
                branch_name=feature_branch,
                title=title,
                body=body,
            )
